### ISSUE TITLE
DeprecationWarning because of the rename from ethereum-utils to eth-utils

### ISSUE THREAD

**Issue by markguo40** [miguelmota/python-etherdelta#6]
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import etherdelta
  File "/anaconda3/lib/python3.6/site-packages/etherdelta/__init__.py", line 12, in <module>
    import web3
  File "/anaconda3/lib/python3.6/site-packages/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "/anaconda3/lib/python3.6/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/anaconda3/lib/python3.6/site-packages/eth_account/account.py", line 10, in <module>
    from eth_keyfile import (
  File "/anaconda3/lib/python3.6/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/anaconda3/lib/python3.6/site-packages/eth_keyfile/keyfile.py", line 10, in <module>
    from eth_keys import keys
  File "/anaconda3/lib/python3.6/site-packages/eth_keys/__init__.py", line 15, in <module>
    from .main import (  # noqa: F401
  File "/anaconda3/lib/python3.6/site-packages/eth_keys/main.py", line 3, in <module>
    from eth_keys.datatypes import (
  File "/anaconda3/lib/python3.6/site-packages/eth_keys/datatypes.py", line 8, in <module>
    from eth_utils import (
  File "/anaconda3/lib/python3.6/site-packages/eth_utils/__init__.py", line 2, in <module>
    "This library has been renamed to `eth-utils`.  The `ethereum-utils` "
DeprecationWarning: This library has been renamed to `eth-utils`.  The `ethereum-utils` package will no longer recieve updates.  Please update your dependencies accordingly.

**Comment by markguo40** [comment]
This issue comes from web3.py

**Comment by markguo40** [comment]
I found this solution:

You need to uninstall the `ethereum-utils` package in your computer. However other problems will show up. The first one is 
```
File "/anaconda3/lib/python3.6/site-packages/eth_keys/datatypes.py", line 8, in <module>
    from eth_utils import (
ImportError: cannot import name 'big_endian_to_int'
```
If this happen, you need to upgrade your eth_utils library:
```
pip install eth_utils --upgrade
```
This problem should be resolved, and then you will face the second problem:
```
  File "/anaconda3/lib/python3.6/site-packages/web3/contract.py", line 13, in <module>
    from eth_utils import (
ImportError: cannot import name 'coerce_return_to_text'
```
This problem is because your web3 version is not up-to-date. For now, it seems like they have not release the newest version so the safest way is to do:
```
pip install git+git://github.com/ethereum/web3.py.git
```

The problem should be resolve at this point.

**Comment by miguelmota** [comment]
@markguo40 wow thanks for figuring this out! The module has been updated and should be working now
